fix(tooltip) - added predifined position and fixed logic error when finding position
konturio/disaster-ninja-fe pull request #184
Opened 2022-09-27 10:13 UTC by IlyaIzr

2022-09-27 10:39 UTC, Akiyamka requested changes
remove vite.config,ts.js file and add this in gitignore

2022-09-27 10:40 UTC, propakov commented on vite.config.ts.js
> +var __defProp = Object.defineProperty;
i believe this one shouldn't be commited

2022-09-27 10:44 UTC, propakov approved these changes

2022-09-29 10:30 UTC, Akiyamka approved these changes

2022-09-29 10:40 UTC, merged