fix(panels): 12585 - add minimal height for each panel
konturio/disaster-ninja-fe pull request #192
Opened 2022-09-28 17:40 UTC by IlyaIzr

2022-09-29 07:13 UTC, vkozio approved these changes

2022-09-29 10:42 UTC, Akiyamka commented on src/features/layers_panel/components/MapLayersPanel/MapLayersPanel.module.css
>    /* allow resize second child which is content wrap */
any change of structure broke this, what part resizable and max height should be porps

2022-09-29 10:42 UTC, Akiyamka requested changes
move min-height and resizable flag to component props

2022-10-06 13:44 UTC, closed without merging

2022-10-06 13:44 UTC, IlyaIzr commented
closed as the effects will be achieved in another PR https://github.com/konturio/disaster-ninja-fe/pull/201