feat(bivariate-color-manager): 10842 - add legend details info block
konturio/disaster-ninja-fe pull request #86
Opened 2022-08-03 14:57 UTC by propakov

https://kontur.fibery.io/Tasks/Task/Choose-denominators-for-selected-indicators-to-make-layers-(Color-legends-section)-dn-fe-10842

2022-08-04 10:22 UTC, IlyaIzr commented on src/features/bivariate_color_manager/components/LegendWithMap/LegendWithMap.tsx
> +);
I think this component big enough to have separate file

2022-08-04 10:23 UTC, IlyaIzr commented on src/features/bivariate_color_manager/components/LegendWithMap/LegendWithMap.tsx
> +      {label + (mostQualityDenominator ? ` to ${mostQualityDenominator}` : '')}
'to' will need translation

2022-08-04 10:28 UTC, IlyaIzr requested changes
also `joinAndCapitalizeItems(direction)` is a bit confusing to read, even considering direction is []

2022-08-04 11:58 UTC, propakov commented
> also `joinAndCapitalizeItems(direction)` is a bit confusing to read, even considering direction is []

I remember we've renamed it already by @Akiyamka request. 
@IlyaIzr Do you have any suggestions?

2022-08-05 13:18 UTC, propakov commented
@IlyaIzr updated naming approach.

2022-08-07 09:31 UTC, IlyaIzr approved these changes

2022-08-08 06:12 UTC, merged