feat(19715): integrate breadcrumbs component into drug flow
konturio/disaster-ninja-fe pull request #869
Opened 2024-10-18 07:56 UTC by Natallia-Harshunova

https://kontur.fibery.io/Tasks/Task/Integrate-map-breadcrumbs-component-into-drag-flow-19715

2024-10-18 14:00 UTC, Natallia-Harshunova commented on src/features/breadcrumbs/BreadcrumbsPanel.tsx
> +};
what do you mean?

2024-10-18 18:09 UTC, Komzpa commented
> drug flow
![image](https://github.com/user-attachments/assets/ae0b43e6-dbe0-4796-bad6-09dd422184f5)

2024-10-18 18:13 UTC, Komzpa commented on src/features/breadcrumbs/BreadcrumbsPanel.tsx
> +};
@coderabbitai remember that we are supporting users dragging map over an ocean to view the cyclone details and trying to zoom out of the blue map. The experience inside "no country" still should allow navigation.

2024-10-18 18:15 UTC, Komzpa commented on src/features/breadcrumbs/atoms/breadcrumbsItemsAtom.ts
> +  currentMapPositionAtom.setCurrentMapBbox.dispatch(bbox);
@coderabbitai remember that we use the map in spherical mercator (EPSG:3857) where the poles are not representable

2024-10-19 19:10 UTC, vkozio requested changes
marked relevant rabbit comments, please pay attention

2024-10-19 19:10 UTC, vkozio commented on src/features/breadcrumbs/BreadcrumbsPanel.tsx
> +  label: i18n.t('no_breadcrumbs_label'),
i18n.t('zoom_to_the_whole_world') please.
Translation keys are not perfect, but let's not make them worse.

2024-10-19 19:10 UTC, vkozio commented on src/features/breadcrumbs/BreadcrumbsPanel.tsx
> +      <Breadcrumbs items={options.reverse()} onClick={clickHandler} />
we have .toReversed() but I'd suggest to create options array in proper order initially

2024-10-21 09:14 UTC, albaranau commented on src/core/api/boundaries.ts
> +    '/boundaries',
Maybe we want an alternative endpoint here? `/boundaries` returns GeoJSONs, and they can be pretty heavy
![image](https://github.com/user-attachments/assets/f0255382-6978-439b-a8ce-1b66c60202e2)

upd: it's probably okay for now, if it's an issue, we should create a separate ticket

2024-10-21 09:14 UTC, albaranau commented on src/core/localization/translations/en/common.json
> +  "no_breadcrumbs_label": "Zoom to the whole world",
Maybe "zoom_to_world" (or similar) would be a better key? It's a string for "zoom to the whole world" button, not for info "no breadcrumbs" label.

2024-10-21 09:24 UTC, Natallia-Harshunova commented on src/core/api/boundaries.ts
> +    '/boundaries',
Yes, let's bring this discussion to the next meeting, but for this pr leave it as it is

2024-10-23 12:10 UTC, amurKontur approved these changes

2024-10-24 14:36 UTC, vkozio approved these changes

2024-10-24 14:40 UTC, merged